### PR TITLE
Added two new tests for verifying shadow of shadow signal functionality

### PR DESCRIPTION
**Pull request by udara28**
Added bench_SliceSlicedSignal, test_SliceSlicedSignal and bench_ConcatConcatedSignal, test_ConcatConcatedSignal

### CODE REVIEW

**Comment by jandecaluwe** [comment]
Still not sure whether we should actually support shadow of shadow ...

**Comment by cfelton** [comment]
@jandecaluwe this has come up a couple time by users (most recently on IRC), if we decide not to support shadow-of-shadow we should consider throwing an error.  We should be able to detect the type (SignalType or ShadowType) but I haven't investigated (don't shoot the messenger :)

**Comment by cfelton** [comment]
@jck, we are attempting to work through these PRs and get them merge (MERGE-VEMBER), @jck if you could merge these after we get them reviewed that would be great.  I don't know if we need @udara28 to update this PR to resolve the conflict?

**Comment by jandecaluwe** [comment]
python3 complains about indentation issues. Please fix.

**Comment by jandecaluwe** [comment]
Also, please merge with latest master. The travis config has been updated and this will be necessary to make the tests work. I will merge the PR when the tests pass.

**Comment by udara28** [comment]
@jandecaluwe I have merged the latest master and added the tests. Please merge this pull request.

**Pull request merged**
