### PR TITLE
Raise traceSignals to DeprecationWarning from UserWarning

### PR DESCRIPTION
**Pull request by davekeeshan**
Missed this one when i changed analyze and verify to DeprecationWarning.  Updated code and added a test.

### CODE REVIEW

**Comment by helloworld-crypto** [comment]
So how can I fix this problem: 'traceSignals(): Deprecated usage: See http://dev.myhdl.org/meps/mep-114.html'
My Python version 3.7.6 and myhdl version 0.11

**Comment by josyb** [comment]
By using the correct simulation syntax, e.g.:
```python
    dft = tb_pingpongbuffer()
    dft.config_sim(trace=True, tracebackup=False, directory='vcd')
    dft.run_sim()
```

**Comment by helloworld-crypto** [comment]
Thank you for promptly reply
But my testbench has mutiple return, so it returns a tuple, for example:
```
def testbench():
    ...
    return framectrl, clkgen, stimulus
```
So, my program raises another error: 'tuple' object has no attribute 'config_sim'

**Comment by josyb** [comment]
Perhaps show some more code next time?

You need to decorate all code returning generators with the `@block` decorator - as you can read in [MEP114]( http://dev.myhdl.org/meps/mep-114.html)

```python
@block
def testbench():
    ...
    return framectrl, clkgen, stimulus
```

**Pull request merged**
