### PR TITLE
added key in dict check before access

### PR DESCRIPTION
**Pull request by cfelton**
Was reviewing some code and ran into a complicated modeling case when a signal was buried deep inside a combination of dictionary and classes.  The node being evaluate was not in the symbol dict.  Adding the key check before accessing resolved the issue.

### CODE REVIEW

**Comment by jck** [comment]
Chris,
Can you try that case with my issue_82 branch?
( `pip install https://github.com/jck/myhdl/archive/issue_82.zip` in a virtualenv)

**Comment by cfelton** [comment]
@jck same error with the issue_82.zip version tested in a virtualenv.

**Comment by jandecaluwe** [comment]
I am worried that this change would mask real issues?

**Comment by cfelton** [comment]
@jandecaluwe would adding a warning be sufficient?  My thought is this is a special case where Signals, used in modeling, are embedded in complex structures that are not convertible.  The chances of seeing this with convertible interfaces is unlikely.

I agree, I don't know the mechanism why certain signals are add to the dict and some are not (the worry is warranted, the actual fix would verify the absence of a signal is expected).

**Comment by jck** [comment]
@cfelton Could you provide an example which triggers this issue? I will try fixing it.

**Comment by cfelton** [comment]
Closing this pull-request per the comments, need a more general solution.

**Pull request closed without merging**
