### PR TITLE
Support Verilator

### PR DESCRIPTION
**Pull request by wsnyder**
This is a fairly large addition to support Verilator. This patch requires the earlier pull request 240 or the tests will not pass.

Please see the edits to the documentation as to how this works, it's a bit different than other simulators and hopefully acceptable.

### CODE REVIEW

**Comment by josyb** [comment]
But #240 doesn't pass the Travis-CI tests ...
Sometimes it is wise to hold your horses and wait for the tests to pass.
Did you run the test on your local machine?

**Comment by wsnyder** [comment]
This passes on my machine running the cosim test with Verilator.

As far as I can tell Travis-CI is broken.  For example the first error is

/bin/sh: 1: ghdl: not found

Which I am presuming indicates something misconfigured in the tests in general. 

Does Travis-CI really pass in master? Can't figure out how to check.

**Comment by wsnyder** [comment]
From what I can determine one needs write access to the repository to retrigger a travis build off master, could you please try that?

https://stackoverflow.com/questions/17606874/trigger-a-travis-ci-rebuild-without-pushing-a-commit

Also, can you please comment on if the patch set looks sane, ignoring tests?

**Comment by josyb** [comment]
I noticed that Travis-CI GHDL problem earlier today (see https://gitter.im/myhdl/myhdl)
I don't have write-access to the MyHDL repo ...
I sent a ping to @jck to have a look at that.

I can't comment on the Verilator support (I'm not a expert on cosimulation ...)
The fix for #238 does however throw an error which needs repairing (IMHO)

**Comment by cfelton** [comment]
@wsnyder can you update your branch (merge with the latest master), the ghdl issues have been fixed in the master.

**Comment by wsnyder** [comment]
Sorry, lost track of this and I'm not looking at myhdl any longer.

**Pull request closed without merging**
